server:
  servlet:
    context-path: /api
    session:
      timeout: 30m

spring:
  application:
    name: board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: board
    password: board1234
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 100
    database: mysql
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false
redis:
  expire:
    default-time: 600

logging:
  level:
    root: debug
